// src/app/components/Web/Layouts/header/header.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-header',
  imports: [RouterLink],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HeaderComponent {

}

<!-- Desktop -->
<header
  class="navbar navbar-expand-sm bg-primary d-none d-sm-block d-lg-block d-xl-block"
>
  <div class="container-xl">
    <div class="navbar-collapse collapse rounded">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a
            [routerLink]="['/page/dip']"
            class="nav-link px-1 text-white"
            target="_blank"
            href="#"
          >
            <span class="text-white">DIP</span>
          </a>
        </li>
        <li class="nav-item">
          <span class="px-1" target="_blank" href="#">
            <span class="text-white">|</span>
          </span>
        </li>
        <li class="nav-item">
          <a
            [routerLink]="['/page/transformacion-digital']"
            class="nav-link px-1 text-white"
            target="_blank"
          >
            <span class="text-white">Transformación Digital</span>
          </a>
        </li>
        <li class="nav-item">
          <span class="px-1" target="_blank" href="#">
            <span class="text-white">|</span>
          </span>
        </li>
        <li class="nav-item">
          <a
            [routerLink]="['/page/ley-del-lobby']"
            class="nav-link px-1 text-white"
            target="_blank"
          >
            <span class="text-white">Ley del Lobby</span>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a
            class="nav-link px-1 text-white"
            target="_blank"
            href="https://www.instagram.com/muniarica/"
          >
            <span class="nav-link-icon text-white"
              ><!-- Download SVG icon from http://tabler-icons.io/i/home -->
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="icon icon-tabler icons-tabler-outline icon-tabler-brand-instagram"
              >
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <path
                  d="M4 8a4 4 0 0 1 4 -4h8a4 4 0 0 1 4 4v8a4 4 0 0 1 -4 4h-8a4 4 0 0 1 -4 -4z"
                />
                <path d="M9 12a3 3 0 1 0 6 0a3 3 0 0 0 -6 0" />
                <path d="M16.5 7.5v.01" />
              </svg>
            </span>
          </a>
        </li>
        <li class="nav-item">
          <a
            class="nav-link px-1 text-white"
            target="_blank"
            href="https://www.facebook.com/MunicipalidaddeArica"
          >
            <span class="nav-link-icon text-white"
              ><!-- Download SVG icon from http://tabler-icons.io/i/home -->
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="icon icon-tabler icons-tabler-outline icon-tabler-brand-facebook"
              >
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <path
                  d="M7 10v4h3v7h4v-7h3l1 -4h-4v-2a1 1 0 0 1 1 -1h3v-4h-3a5 5 0 0 0 -5 5v2h-3"
                />
              </svg>
            </span>
          </a>
        </li>
        <li class="nav-item">
          <a
            class="nav-link px-1 text-white"
            target="_blank"
            href="https://www.flickr.com/photos/muniarica/"
          >
            <span class="nav-link-icon text-white"
              ><!-- Download SVG icon from http://tabler-icons.io/i/home -->
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="icon icon-tabler icons-tabler-outline icon-tabler-brand-flickr"
              >
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <path d="M7 12m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0" />
                <path d="M17 12m-3 0a3 3 0 1 0 6 0a3 3 0 1 0 -6 0" />
              </svg>
            </span>
          </a>
        </li>
        <li class="nav-item">
          <a
            class="nav-link px-1 text-white"
            target="_blank"
            href="https://www.youtube.com/@CanalMunicipalidadArica"
          >
            <span class="nav-link-icon text-white"
              ><!-- Download SVG icon from http://tabler-icons.io/i/home -->
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="icon icon-tabler icons-tabler-outline icon-tabler-brand-youtube"
              >
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <path
                  d="M2 8a4 4 0 0 1 4 -4h12a4 4 0 0 1 4 4v8a4 4 0 0 1 -4 4h-12a4 4 0 0 1 -4 -4v-8z"
                />
                <path d="M10 9l5 3l-5 3z" />
              </svg>
            </span>
          </a>
        </li>
        <li class="nav-item">
          <a
            class="nav-link px-1 text-white"
            target="_blank"
            href="https://www.tiktok.com/@aricamunicipalidad"
          >
            <span class="nav-link-icon text-white"
              ><!-- Download SVG icon from http://tabler-icons.io/i/home -->
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="icon icon-tabler icons-tabler-outline icon-tabler-brand-tiktok"
              >
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <path
                  d="M21 7.917v4.034a9.948 9.948 0 0 1 -5 -1.951v4.5a6.5 6.5 0 1 1 -8 -6.326v4.326a2.5 2.5 0 1 0 4 2v-11.5h4.083a6.005 6.005 0 0 0 4.917 4.917z"
                />
              </svg>
            </span>
          </a>
        </li>
        <li class="nav-item">
          <a
            class="nav-link px-1 text-white"
            target="_blank"
            href="https://open.spotify.com/user/31afurm6j5wkukrjpmjqx7oj5z7y"
          >
            <span class="nav-link-icon text-white"
              ><!-- Download SVG icon from http://tabler-icons.io/i/home -->
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="icon icon-tabler icons-tabler-outline icon-tabler-brand-spotify"
              >
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <path d="M12 12m-9 0a9 9 0 1 0 18 0a9 9 0 1 0 -18 0" />
                <path d="M8 11.973c2.5 -1.473 5.5 -.973 7.5 .527" />
                <path d="M9 15c1.5 -1 4 -1 5 .5" />
                <path d="M7 9c2 -1 6 -2 10 .5" />
              </svg>
            </span>
          </a>
        </li>
      </ul>
    </div>
  </div>
</header>

// src/components/Layouts/Web/Header.vue
<template>
    <!-- Desktop -->
    <header
        class="navbar navbar-expand-md d-print-none sticky-top bg-primary shadow-none d-none d-md-block d-lg-block d-xl-block">
        <div class="container-xl">
            <div class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">
                <router-link to="/">
                    <img src="/img/logos/logo.png" alt="logo-muniarica" class="mx-auto d-block img-logo-desktop" />
                </router-link>
            </div>
            <button class="navbar-toggler text-white" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse mt-2 mb-3 rounded" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link text-white" target="_blank" href="http://127.0.0.1:8080/vistas/56">
                            <span
                                class="nav-link-icon text-white"><!-- Download SVG icon from http://tabler-icons.io/i/home -->
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                    fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                    stroke-linejoin="round" class="icon">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                    <path d="M5 12l-2 0l9 -9l9 9l-2 0"></path>
                                    <path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7"></path>
                                    <path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6"></path>
                                </svg>
                            </span>
                            <span class="nav-link-title">
                                Contáctanos
                            </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" target="_blank" href="https://intranet.imaarica.cl/anexos">
                            <span
                                class="nav-link-icon text-white"><!-- Download SVG icon from http://tabler-icons.io/i/home -->
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                    fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                    stroke-linejoin="round" class="icon">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                    <path d="M5 12l-2 0l9 -9l9 9l-2 0"></path>
                                    <path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7"></path>
                                    <path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6"></path>
                                </svg>
                            </span>
                            <span class="nav-link-title">
                                Anexos Municipales
                            </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" target="_blank" href="https://intranet.imaarica.cl/anexos">
                            <span
                                class="nav-link-icon text-white"><!-- Download SVG icon from http://tabler-icons.io/i/home -->
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                    fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                    stroke-linejoin="round" class="icon">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                    <path d="M5 12l-2 0l9 -9l9 9l-2 0"></path>
                                    <path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7"></path>
                                    <path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6"></path>
                                </svg>
                            </span>
                            <span class="nav-link-title">
                                Celulares Municipales
                            </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-warning" target="_blank"
                            href="https://intranetarica.smc.cl/login.aspx?ReturnUrl=%2f">
                            <span
                                class="nav-link-icon d-md-none d-lg-inline-block text-white "><!-- Download SVG icon from http://tabler-icons.io/i/home -->
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                    fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                    stroke-linejoin="round" class="icon">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                    <path d="M5 12l-2 0l9 -9l9 9l-2 0"></path>
                                    <path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7"></path>
                                    <path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6"></path>
                                </svg>
                            </span>
                            <span class="nav-link-title ">
                                Sistema de RRHH
                            </span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </header>

    <!-- Movile -->
    <header
        class="navbar navbar-expand-md d-print-none sticky-top bg-primary shadow-none d-block d-md-none d-lg-none d-xl-none">
        <div class="container-fluid">
            <div class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-0 pe-md-3">
                <router-link to="/">
                    <img src="/img/logos/logo.png" alt="logo-muniarica" class="mx-auto d-block img-logo-movile" />
                </router-link>
            </div>
            <button class="navbar-toggler text-white" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse mt-2 mb-3 rounded" id="navbarSupportedContent">
                <ul class="navbar-nav w-100">
                    <li class="nav-item">
                        <a class="nav-link text-white" target="_blank" href="http://127.0.0.1:8080/vistas/56">
                            <span
                                class="nav-link-icon text-white"><!-- Download SVG icon from http://tabler-icons.io/i/home -->
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                    fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                    stroke-linejoin="round" class="icon">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                    <path d="M5 12l-2 0l9 -9l9 9l-2 0"></path>
                                    <path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7"></path>
                                    <path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6"></path>
                                </svg>
                            </span>
                            <span class="nav-link-title">
                                Contáctanos
                            </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" target="_blank" href="https://intranet.imaarica.cl/anexos">
                            <span
                                class="nav-link-icon text-white"><!-- Download SVG icon from http://tabler-icons.io/i/home -->
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                    fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                    stroke-linejoin="round" class="icon">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                    <path d="M5 12l-2 0l9 -9l9 9l-2 0"></path>
                                    <path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7"></path>
                                    <path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6"></path>
                                </svg>
                            </span>
                            <span class="nav-link-title">
                                Anexos Municipales
                            </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" target="_blank" href="https://intranet.imaarica.cl/anexos">
                            <span
                                class="nav-link-icon text-white"><!-- Download SVG icon from http://tabler-icons.io/i/home -->
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                    fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                    stroke-linejoin="round" class="icon">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                    <path d="M5 12l-2 0l9 -9l9 9l-2 0"></path>
                                    <path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7"></path>
                                    <path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6"></path>
                                </svg>
                            </span>
                            <span class="nav-link-title">
                                Celulares Municipales
                            </span>
                        </a>
                    </li>
                    <li class="nav-item pt-3">
                        <a class="btn btn-warning" target="_blank"
                            href="https://intranetarica.smc.cl/login.aspx?ReturnUrl=%2f">
                            <span
                                class="nav-link-icon d-md-none d-lg-inline-block text-white "><!-- Download SVG icon from http://tabler-icons.io/i/home -->
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                    fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                    stroke-linejoin="round" class="icon">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                    <path d="M5 12l-2 0l9 -9l9 9l-2 0"></path>
                                    <path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7"></path>
                                    <path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6"></path>
                                </svg>
                            </span>
                            <span class="nav-link-title ">
                                Sistema de RRHH
                            </span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </header>

</template>
<style scoped>
.img-logo-desktop {
    max-width: 255px;
    height: auto;
}

.img-logo-movile {
    max-width: 276px;
    height: auto;
}
</style>
