// src/components/Auth/ResetPassword.vue
<template>
    <div class="d-flex flex-column bg-white vh-100">
        <div class="page page-center">
            <div class="container py-4">
                <div class="text-center mb-4">
                    <a href="."
                        class="navbar-brand navbar-brand-autodark d-none d-md-block d-lg-block d-xl-block d-xxl-block"><img
                            src="/img/auth/reset-password.svg" style="width: 200px" alt="" /></a>
                </div>
                <div class="card-md">
                    <div class="card-body">
                        <form @submit.prevent="submit">
                            <h2 class="card-title text-center mb-4">Reestablece tu contraseña</h2>
                            <div class="mb-3">
                                <label for="label-password" class="form-label">Contraseña </label>
                                <div class="row g-2">
                                    <div class="col">
                                        <input :type="showPassword ? 'text' : 'password'" v-model="password"
                                            class="form-control" :class="{ 'is-invalid': validationErrors.password }"
                                            id="label-password">
                                        <div class="invalid-feedback" v-if="validationErrors.password">
                                            {{ validationErrors.password[0] }}
                                        </div>
                                    </div>
                                    <div class="col-auto">
                                        <a @click.prevent="toggleShowPassword" title="Mostrar contraseña" href="#"
                                            class="btn btn-icon" aria-label="Button">
                                            <!-- Download SVG icon from http://tabler-icons.io/i/search -->
                                            <svg v-if="showPassword" xmlns="http://www.w3.org/2000/svg" width="24"
                                                height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                                stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                                                class="icon icon-tabler icons-tabler-outline icon-tabler-eye">
                                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                <path d="M10 12a2 2 0 1 0 4 0a2 2 0 0 0 -4 0" />
                                                <path
                                                    d="M21 12c-2.4 4 -5.4 6 -9 6c-3.6 0 -6.6 -2 -9 -6c2.4 -4 5.4 -6 9 -6c3.6 0 6.6 2 9 6" />
                                            </svg>
                                            <svg v-else xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                                viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                                                stroke-linecap="round" stroke-linejoin="round"
                                                class="icon icon-tabler icons-tabler-outline icon-tabler-eye-closed">
                                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                <path d="M21 9c-2.4 2.667 -5.4 4 -9 4c-3.6 0 -6.6 -1.333 -9 -4" />
                                                <path d="M3 15l2.5 -3.8" />
                                                <path d="M21 14.976l-2.492 -3.776" />
                                                <path d="M9 17l.5 -4" />
                                                <path d="M15 17l-.5 -4" />
                                            </svg>
                                        </a>
                                    </div>

                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="label-password-confirm" class="form-label">Confirmar Contraseña </label>
                                <div class="row g-2">
                                    <div class="col">
                                        <input :type="showPasswordConfirm ? 'text' : 'password'"
                                            v-model="password_confirmation" class="form-control"
                                            :class="{ 'is-invalid': validationErrors.password_confirmation }"
                                            id="label-password-confirm">
                                        <div class="invalid-feedback" v-if="validationErrors.password_confirmation">
                                            {{ validationErrors.password_confirmation[0] }}
                                        </div>
                                    </div>
                                    <div class="col-auto">
                                        <a @click.prevent="toggleShowPasswordConfirm" title="Mostrar contraseña"
                                            href="#" class="btn btn-icon" aria-label="Button">
                                            <!-- Download SVG icon from http://tabler-icons.io/i/search -->
                                            <svg v-if="showPasswordConfirm" xmlns="http://www.w3.org/2000/svg"
                                                width="24" height="24" viewBox="0 0 24 24" fill="none"
                                                stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                                stroke-linejoin="round"
                                                class="icon icon-tabler icons-tabler-outline icon-tabler-eye">
                                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                <path d="M10 12a2 2 0 1 0 4 0a2 2 0 0 0 -4 0" />
                                                <path
                                                    d="M21 12c-2.4 4 -5.4 6 -9 6c-3.6 0 -6.6 -2 -9 -6c2.4 -4 5.4 -6 9 -6c3.6 0 6.6 2 9 6" />
                                            </svg>
                                            <svg v-else xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                                viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                                                stroke-linecap="round" stroke-linejoin="round"
                                                class="icon icon-tabler icons-tabler-outline icon-tabler-eye-closed">
                                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                                <path d="M21 9c-2.4 2.667 -5.4 4 -9 4c-3.6 0 -6.6 -1.333 -9 -4" />
                                                <path d="M3 15l2.5 -3.8" />
                                                <path d="M21 14.976l-2.492 -3.776" />
                                                <path d="M9 17l.5 -4" />
                                                <path d="M15 17l-.5 -4" />
                                            </svg>
                                        </a>
                                    </div>

                                </div>
                            </div>
                            <div class="form-footer">
                                <button v-if="loading" type="submit" class="btn btn-primary w-100" disabled>
                                    <span class="spinner-border spinner-border-sm me-2" role="status"></span>
                                    Cargando...
                                </button>
                                <button v-else type="submit" class="btn btn-primary w-100">
                                    <!-- Download SVG icon from http://tabler-icons.io/i/mail -->
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                        fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                        stroke-linejoin="round"
                                        class="icon icon-tabler icons-tabler-outline icon-tabler-lock-open">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                        <path
                                            d="M5 11m0 2a2 2 0 0 1 2 -2h10a2 2 0 0 1 2 2v6a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2z" />
                                        <path d="M12 16m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0" />
                                        <path d="M8 11v-5a4 4 0 0 1 8 0" />
                                    </svg>
                                    Cambiar contraseña
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>
import { ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useAuthStore } from '@/stores/auth';
import { axiosInstance } from '@/plugins/axios';
import { useToast } from 'vue-toast-notification';
import 'vue-toast-notification/dist/theme-bootstrap.css';

// Instancias de router, route, auth store, and toast
const router = useRouter();
const route = useRoute();
const authStore = useAuthStore();
const $toast = useToast();

// Propiedades reactivas
const password = ref('');
const password_confirmation = ref('');
const showPassword = ref(false);
const showPasswordConfirm = ref(false);
const validationErrors = ref({});
const loading = ref(false);

// Alternar visibilidad de contraseña
const toggleShowPassword = () => {
    showPassword.value = !showPassword.value;
};

const toggleShowPasswordConfirm = () => {
    showPasswordConfirm.value = !showPasswordConfirm.value;
};

// Metodo Submit 
const submit = async () => {
    try {
        loading.value = true;
        validationErrors.value = {};
        const response = await axiosInstance.post('/api/auth/password/reset', {
            password: password.value,
            password_confirmation: password_confirmation.value,
            token: route.query.token,
            email: route.query.email,
        });

        $toast.info(response.data.message, {
            position: 'top-right',
            duration: 3000,
        });

        // Redirigiendo al login
        const { message } = await authStore.login(route.query.rut, password.value);
        $toast.success(message, {
            position: 'top-right',
            duration: 5000,
        });

        // Reestablecer campos
        password.value = '';
        password_confirmation.value = '';

        // Navegar a Home
        router.push({ name: 'Home' });
    } catch (error) {
        handleRequestError(error);
    } finally {
        loading.value = false;
    }
};

// Función para manejar errores de la API
const handleRequestError = (error) => {
    if (error.response) {
        const status = error.response.status;
        const message = error.response.data.message || 'Error del Sistema';

        switch (status) {
            case 401:
                // Error 401: No autorizado
                $toast.error('No autorizado. ' + message, { position: 'top-right' });
                break;
            case 403:
                // Error 403: Prohibido
                $toast.error('Prohibido. ' + message, { position: 'top-right' });
                break;
            case 404:
                // Error 404: No encontrado
                $toast.error( message, { position: 'top-right' });
                break;
            case 429:
                // Error 429: Demasiadas solicitudes
                $toast.error('Demasiadas solicitudes. ' + message, { position: 'top-right' });
                break;
            case 500:
                // Error 500: Error interno del servidor
                $toast.error('Error interno del servidor. ' + message, { position: 'top-right' });
                break;
            case 422:
                // Error 422: Error de validación
                validationErrors.value = error.response.data.errors;
                $toast.error('Error de validación. ', { position: 'top-right' });
                break;
            default:
                if (error.response.data && error.response.data.errors) {
                    $toast.error('Error del Sistema de Servidor. ' + error.response.data.errors, { position: 'top-right' });

                } else {
                    $toast.error(`Error del Sistema ${error}`, { position: 'top-right' });
                }
        }
    } else {
        $toast.error(`Error del Sistema ${error}`, { position: 'top-right' });
    }
};

</script>

// src/app/components/Auth/reset-password/reset-password.component.ts
import { Component, inject } from '@angular/core';
import {
  FormControl,
  FormGroup,
  Validators,
  ReactiveFormsModule,
  AbstractControl,
  ValidationErrors,
} from '@angular/forms';
import { AuthService } from '@services/auth.service';
import { ActivatedRoute, RouterLink } from '@angular/router';

@Component({
  selector: 'app-reset-password',
  imports: [ReactiveFormsModule, RouterLink],
  templateUrl: './reset-password.component.html',
  styleUrl: './reset-password.component.css',
})
export class ResetPasswordComponent {
  public loading: boolean = false;
  public errorMessage: string = '';
  public successMessage: string = '';
  public showPassword: boolean = false;
  public token: string = '';
  public email: string = '';

  public authService = inject(AuthService);

  constructor(private route: ActivatedRoute) {}

  form: FormGroup = new FormGroup(
    {
      password: new FormControl('', [
        Validators.required,
        Validators.minLength(8),
        this.passwordValidator(),
      ]),
      password_confirmation: new FormControl('', [Validators.required]),
    },
    { validators: this.passwordsMatch.bind(this) }
  );

  resetPassword(): void {
    this.loading = true;
    this.errorMessage = '';
    this.successMessage = '';

    this.token = this.route.snapshot.paramMap.get('token') || '';
    this.route.queryParams.subscribe((params) => {
      this.email = params['email'] || '';
    });

    this.authService
      .resetPassword({
        token: this.token,
        email: this.email,
        password: this.form.value.password,
        password_confirmation: this.form.value.password_confirmation,
      })
      .subscribe({
        next: (response: string) => {
          this.loading = false;
          this.successMessage = response;
          this.form.value.password = '';
          this.form.value.password_confirmation = '';
        },
        error: (error) => {
          this.loading = false;
          if (error.status === 422) {
            this.errorMessage = this.processErrors(error.error.errors);
          } else {
            this.errorMessage = error.error;
          }
        },
      });
  }

  toggleShowPassword(): void {
    this.showPassword = !this.showPassword;
  }

  passwordsMatch(control: AbstractControl): ValidationErrors | null {
    const password = control.get('password')?.value;
    const confirmPassword = control.get('password_confirmation')?.value;
    return password && confirmPassword && password === confirmPassword
      ? null
      : { passwordsNotMatch: 'Las contraseñas no coinciden' };
  }

  processErrors(errors: { [key: string]: string[] }): string {
    const errorList = Object.keys(errors)
      .flatMap((key) => errors[key])
      .map((error) => `- ${error}</br>`)
      .join('');

    // Retornar el HTML como un string
    return `${errorList}`;
  }

  passwordValidator() {
    return (control: AbstractControl): ValidationErrors | null => {
      const password = control.value;

      // Validar que la contraseña tenga al menos una letra mayúscula
      const hasUpperCase = /[A-Z]/.test(password);

      // Validar que la contraseña tenga al menos una letra minúscula
      const hasLowerCase = /[a-z]/.test(password);

      // Validar que la contraseña tenga al menos un número
      const hasNumber = /\d/.test(password);

      // Validar que la contraseña tenga al menos un carácter especial
      const hasSpecialChar = /[!@#$%^&*(),.?":{}|<>]/.test(password);

      // Verificar que todas las condiciones se cumplan
      if (hasUpperCase && hasLowerCase && hasNumber && hasSpecialChar) {
        return null; // Si la contraseña cumple con todos los requisitos, es válida
      } else {
        return {
          passwordStrength:
            'La contraseña debe contener al menos: 8 caracteres, una letra mayúscula, una letra minúscula, un número y un carácter especial.',
        };
      }
    };
  }
}

<!doctype html>
<html lang="es">
  <body class="d-flex flex-column">
    <div class="page page-center">
      <div class="container-tight container py-4">
        <div class="mt-2 mb-4 text-center">
          <img src="/assets/img/logos/logo-blanco.png" alt="Logo-muniarica" />
        </div>
        <form
          class="card card-md"
          [formGroup]="form"
          (ngSubmit)="resetPassword()"
        >
          <div class="card-body">
            <h2 class="card-title mb-4 text-center">Restablecer contraseña</h2>
            <div class="mb-3">
              @if (errorMessage) {
                <div
                  class="alert alert-important alert-danger alert-dismissible"
                  role="alert"
                >
                  <div class="d-flex">
                    <div>
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        class="icon alert-icon"
                        width="24"
                        height="24"
                        viewBox="0 0 24 24"
                        stroke-width="2"
                        stroke="currentColor"
                        fill="none"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                      >
                        <path
                          stroke="none"
                          d="M0 0h24v24H0z"
                          fill="none"
                        ></path>
                        <circle cx="12" cy="12" r="9"></circle>
                        <line x1="12" y1="8" x2="12" y2="12"></line>
                        <line x1="12" y1="16" x2="12.01" y2="16"></line>
                      </svg>
                    </div>
                    <div>
                      <div [innerHTML]="errorMessage" class="ms-1">
                        {{ errorMessage }}
                      </div>
                    </div>
                  </div>
                  <a
                    class="btn-close btn-close-white"
                    data-bs-dismiss="alert"
                    aria-label="close"
                  ></a>
                </div>
              }
              @if (successMessage) {
                <div
                  class="alert alert-important alert-success alert-dismissible"
                  role="alert"
                >
                  <div class="d-flex">
                    <div>
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="24"
                        height="24"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="2"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        class="icon icon-tabler icons-tabler-outline icon-tabler-check"
                      >
                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                        <path d="M5 12l5 5l10 -10" />
                      </svg>
                    </div>
                    <span class="ms-1">{{ successMessage }}</span>
                  </div>
                  <a
                    class="btn-close btn-close-white"
                    data-bs-dismiss="alert"
                    aria-label="close"
                  ></a>
                </div>
              }
              <div>
                <div class="alert alert-info" role="alert">
                  <div class="d-flex">
                    <div>
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        class="icon alert-icon"
                        width="24"
                        height="24"
                        viewBox="0 0 24 24"
                        stroke-width="2"
                        stroke="currentColor"
                        fill="none"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                      >
                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                        <circle cx="12" cy="12" r="9" />
                        <line x1="12" y1="8" x2="12.01" y2="8" />
                        <polyline points="11 12 12 12 12 16 13 16" />
                      </svg>
                    </div>
                    <div>
                      <h4 class="alert-title" style="margin-left: 5px">
                        Tu contraseña debe cumplir con los siguientes
                        requisitos:
                      </h4>
                      <div class="text-secondary">
                        <ul>
                          <li>Tener al menos 8 caracteres de longitud.</li>
                          <li>
                            Incluir al menos una letra mayúscula y una letra
                            minúscula.
                          </li>
                          <li>Al menos una letra minúscula.</li>
                          <li>
                            Incluir al menos un carácter especial (por ejemplo,
                            #, $, !, %, etc.).
                          </li>
                          <li>
                            No debe haber sido comprometida en brechas de
                            seguridad.
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div>
                <label class="form-label">Nueva contraseña</label>
                <input
                  formControlName="password"
                  [type]="showPassword ? 'text' : 'password'"
                  class="form-control"
                  id="label-password"
                  [class.is-invalid]="
                    form.get('password')?.invalid &&
                    (form.get('password')?.touched ||
                      form.get('password')?.dirty)
                  "
                  [class.is-valid]="
                    form.get('password')?.valid &&
                    (form.get('password')?.touched ||
                      form.get('password')?.dirty)
                  "
                />
                @if (
                  (form.get("password")?.invalid &&
                    form.get("password")?.touched) ||
                  form.get("password")?.dirty
                ) {
                  @if (form.get("password")?.hasError("required")) {
                    <span class="invalid-input">
                      La contraseña es obligatoria.
                    </span>
                  } @else if (form.get("password")?.hasError("minlength")) {
                    <span class="invalid-input">
                      La contraseña debe tener al menos 8 caracteres.
                    </span>
                  } @else if (form.get("password")?.hasError("pattern")) {
                    <span class="invalid-input">
                      La contraseña debe contener al menos una letra mayúscula,
                      una letra minúscula, un número y un carácter especial.
                    </span>
                  }
                } @else {
                  <span class="invalid-input">&nbsp;</span>
                }
              </div>
              <div>
                <label class="form-label">Confirmar contraseña</label>
                <input
                  formControlName="password_confirmation"
                  [type]="showPassword ? 'text' : 'password'"
                  class="form-control"
                  id="label-password_confirmation"
                  [class.is-invalid]="
                    form.get('password_confirmation')?.invalid &&
                    (form.get('password_confirmation')?.touched ||
                      form.get('password_confirmation')?.dirty)
                  "
                />
                @if (
                  (form.get("password_confirmation")?.invalid &&
                    form.get("password_confirmation")?.touched) ||
                  form.get("password_confirmation")?.dirty
                ) {
                  @if (
                    form.get("password_confirmation")?.hasError("required")
                  ) {
                    <span class="invalid-input">
                      La confirmación de la contraseña es obligatoria.
                    </span>
                  } @else if (
                    form.get("password_confirmation")?.valid &&
                    form.get("passwordsMatch")?.touched
                  ) {
                    <span class="invalid-input">
                      Las contraseñas no coinciden.
                    </span>
                  }
                } @else {
                  <span class="invalid-input">&nbsp;</span>
                }
              </div>
              <div class="pt-2">
                <div>
                  <label class="form-check">
                    <input
                      (click)="toggleShowPassword()"
                      class="form-check-input"
                      type="checkbox"
                    />
                    <span class="form-check-label">Mostrar contraseña</span>
                  </label>
                </div>
              </div>
            </div>
            <div class="form-footer mt-0">
              @if (loading) {
                <button type="button" class="btn btn-primary w-100" disabled>
                  <span
                    class="spinner-border spinner-border-sm me-2"
                    role="status"
                  ></span>
                  Cargando...
                </button>
              } @else {
                <button
                  type="submit"
                  [disabled]="form.invalid"
                  class="btn btn-primary w-100"
                >
                  <!-- Download SVG icon from http://tabler-icons.io/i/mail -->
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    class="icon"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    stroke-width="2"
                    stroke="currentColor"
                    fill="none"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  >
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <path
                      d="M3 7a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-10z"
                    />
                    <path d="M3 7l9 6l9 -6" />
                  </svg>
                  Restablecer contraseña
                </button>
              }
            </div>
          </div>
        </form>
        <div class="text-secondary mt-3 text-center">
          <a [routerLink]="['/login']" class="text-white">Volver al inicio</a>
        </div>
      </div>
    </div>
  </body>
</html>
