// src/components/Auth/ForgotPassword.vue
<template>

    <div class="d-flex flex-column bg-white">
        <div class="row g-0 flex-fill">
            <div class="col-12 col-lg-6 col-xl-8 d-none d-lg-block">
                <img src="https://preview.tabler.io/static/photos/finances-us-dollars-and-bitcoins-currency-money-2.jpg"
                    height="300" class="bg-cover h-100 min-vh-100" alt="">
            </div>
            <div
                class="col-12 col-lg-6 col-xl-4 border-top-wide border-primary d-flex flex-column justify-content-center">
                <div class="container container-tight my-5 px-lg-5">
                    <h2 class="h2 text-center mb-3">
                        ¿Te olvidaste la contraseña?
                    </h2>
                    <form @submit.prevent="submit">
                        <p class="text-muted">Ingresa la dirección de correo electrónico asociada a tu cuenta y te
                            enviaremos un enlace para restablecer tu contraseña.</p>
                        <div class="mb-3">
                            <label class="form-label">Correo electrónico </label>
                            <input v-model="email" type="email" class="form-control"
                                :class="{ 'is-invalid': validationErrors.email }"
                                placeholder="example@municipalidadarica.cl">
                            <div class="invalid-feedback" v-if="validationErrors.email">
                                {{ validationErrors.email[0] }}
                            </div>
                        </div>
                        <div class="form-footer">
                            <button v-if="loading" type="submit" class="btn btn-primary w-100" disabled>
                                <span class="spinner-border spinner-border-sm me-2" role="status"></span>
                                Cargando...
                            </button>
                            <button v-else type="submit" class="btn btn-primary w-100">
                                <!-- Download SVG icon from http://tabler-icons.io/i/mail -->
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24"
                                    viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                                    stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                    <path
                                        d="M3 7a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-10z" />
                                    <path d="M3 7l9 6l9 -6" />
                                </svg>
                                Enviar enlace para restablecer contraseña
                            </button>
                        </div>
                    </form>
                    <div class="text-center text-secondary mt-3">
                        <router-link to="/login" tabindex="-1">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                stroke-linejoin="round"
                                class="icon icon-tabler icons-tabler-outline icon-tabler-chevron-left">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                <path d="M15 6l-6 6l6 6" />
                            </svg>
                            Volver atrás</router-link>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script setup>
import { ref } from 'vue';
import { axiosInstance } from '@/plugins/axios';
import { useToast } from 'vue-toast-notification';
import 'vue-toast-notification/dist/theme-bootstrap.css';

// Instancia Toast 
const $toast = useToast();

// Propiedades reactivas
const email = ref('');
const validationErrors = ref({});
const loading = ref(false);

// Función para enviar el formulario
const submit = async () => {
    try {
        loading.value = true;
        clearErrors();

        const response = await axiosInstance.post('/api/auth/password/email', {
            email: email.value,
        });

        $toast.success(response.data.message, {
            position: 'top-right',
        });

        email.value = '';
    } catch (error) {
        handleRequestError(error);
    } finally {
        loading.value = false;
    }
};

// Función para limpiar errores
const clearErrors = () => {
    validationErrors.value = {};
};

// Función para manejar errores de la API
const handleRequestError = (error) => {
    if (error.response) {
        const status = error.response.status;
        const message = error.response.data.message || 'Error del Sistema';

        switch (status) {
            case 401:
                // Error 401: No autorizado
                $toast.error('No autorizado. ' + message, { position: 'top-right' });
                break;
            case 403:
                // Error 403: Prohibido
                $toast.error('Prohibido. ' + message, { position: 'top-right' });
                break;
            case 404:
                // Error 404: No encontrado
                $toast.error(message, { position: 'top-right' });
                break;
            case 429:
                // Error 429: Demasiadas solicitudes
                $toast.error('Demasiadas solicitudes. ' + message, { position: 'top-right' });
                break;
            case 500:
                // Error 500: Error interno del servidor
                $toast.error('Error interno del servidor. ' + message, { position: 'top-right' });
                break;
            case 422:
                // Error 422: Error de validación
                validationErrors.value = error.response.data.errors;
                $toast.error('Error de validación. ', { position: 'top-right' });
                break;
            default:
                if (error.response.data && error.response.data.errors) {
                    $toast.error('Error del Sistema de Servidor. ' + error.response.data.errors, { position: 'top-right' });

                } else {
                    $toast.error(`Error del Sistema ${error}`, { position: 'top-right' });
                }
        }
    } else {
        $toast.error(`Error del Sistema ${error}`, { position: 'top-right' });
    }
};

</script>

// src/app/Auth/forgot-password/forgot-password.component.ts
import { Component } from '@angular/core';
import {
  FormControl,
  FormGroup,
  Validators,
  ReactiveFormsModule,
} from '@angular/forms';
import { AuthService } from '../../services/auth.service';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-forgot-password',
  imports: [ReactiveFormsModule, RouterLink],
  templateUrl: './forgot-password.component.html',
  styleUrl: './forgot-password.component.css',
})
export class ForgotPasswordComponent {
  public loading: boolean = false;
  public errorMessage: string = '';
  public successMessage: string = '';

  form: FormGroup = new FormGroup({
    email: new FormControl('', [
      Validators.required,
      Validators.email,
    ]),
  });

  constructor(private authService: AuthService) {}

  forgotPassword(): void {
    this.loading = true;
    this.errorMessage = '';
    this.successMessage = '';

    this.authService.forgotPassword(this.form.value.email).subscribe({
      next: (response: string) => {
        this.loading = false;
        this.successMessage = response;
      },
      error: (error) => {
        this.loading = false;
        if (error.status === 422) {
          this.errorMessage = this.processErrors(error.error.errors);
        } else {
          this.errorMessage = error;
        }
      },
    });
  }

  processErrors(errors: { [key: string]: string[] }): string {
    const errorList = Object.keys(errors)
      .flatMap((key) => errors[key])
      .map((error) => `- ${error}</br>`)
      .join('');

    return `${errorList}`;
  }
}

<!doctype html>
<html lang="es">
  <body class="d-flex flex-column">
    <div class="page page-center">
      <div class="container-tight container py-4">
        <div class="mt-2 mb-4 text-center">
          <img src="/assets/img/logos/logo-blanco.png" alt="Logo-muniarica" />
        </div>
        <form
          class="card card-md"
          [formGroup]="form"
          (ngSubmit)="forgotPassword()"
        >
          <div class="card-body">
            <h2 class="card-title mb-4 text-center">Recuperar contraseña</h2>
            <p class="text-secondary mb-4">
              Ingrese su dirección de correo electrónico y recibirá un enlace
              para restablecer su contraseña.
            </p>
            <div class="mb-3">
              @if (errorMessage) {
                <div
                  class="alert alert-important alert-danger alert-dismissible"
                  role="alert"
                >
                  <div class="d-flex">
                    <div>
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        class="icon alert-icon"
                        width="24"
                        height="24"
                        viewBox="0 0 24 24"
                        stroke-width="2"
                        stroke="currentColor"
                        fill="none"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                      >
                        <path
                          stroke="none"
                          d="M0 0h24v24H0z"
                          fill="none"
                        ></path>
                        <circle cx="12" cy="12" r="9"></circle>
                        <line x1="12" y1="8" x2="12" y2="12"></line>
                        <line x1="12" y1="16" x2="12.01" y2="16"></line>
                      </svg>
                    </div>
                    <div>
                      <span class="ms-1">{{ errorMessage }}</span>
                    </div>
                  </div>
                  <a
                    class="btn-close btn-close-white"
                    data-bs-dismiss="alert"
                    aria-label="close"
                  ></a>
                </div>
              }
              @if (successMessage) {
                <div
                  class="alert alert-important alert-success alert-dismissible"
                  role="alert"
                >
                  <div class="d-flex">
                    <div>
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="24"
                        height="24"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="2"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        class="icon icon-tabler icons-tabler-outline icon-tabler-check"
                      >
                        <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                        <path d="M5 12l5 5l10 -10" />
                      </svg>
                    </div>
                    <span class="ms-1">{{ successMessage }}</span>
                  </div>
                  <a
                    class="btn-close btn-close-white"
                    data-bs-dismiss="alert"
                    aria-label="close"
                  ></a>
                </div>
              }

              <label class="form-label">Email address</label>
              <input
                formControlName="email"
                type="text"
                class="form-control"
                placeholder="12345678-K"
                id="label-email"
                [class.is-invalid]="
                  form.get('email')?.invalid &&
                  (form.get('email')?.touched || form.get('email')?.dirty)
                "
                [class.is-valid]="
                  form.get('email')?.valid &&
                  (form.get('email')?.touched || form.get('email')?.dirty)
                "
              />
              @if (
                (form.get("email")?.invalid && form.get("email")?.touched) ||
                form.get("email")?.dirty
              ) {
                @if (form.get("email")?.hasError("required")) {
                  <span class="invalid-input">El email es obligatorio</span>
                }
                @if (form.get("email")?.hasError("email")) {
                  <span class="invalid-input">
                    El formato del email es inválido.</span
                  >
                }
              } @else {
                <span class="invalid-input">&nbsp;</span>
              }
            </div>
            <div class="form-footer mt-0">
              @if (loading) {
                <button type="button" class="btn btn-primary w-100" disabled>
                  <span
                    class="spinner-border spinner-border-sm me-2"
                    role="status"
                  ></span>
                  Cargando...
                </button>
              } @else {
                <button
                  type="submit"
                  [disabled]="form.invalid"
                  class="btn btn-primary w-100"
                >
                  <!-- Download SVG icon from http://tabler-icons.io/i/mail -->
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    class="icon"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    stroke-width="2"
                    stroke="currentColor"
                    fill="none"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  >
                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                    <path
                      d="M3 7a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-10z"
                    />
                    <path d="M3 7l9 6l9 -6" />
                  </svg>
                  Enviar una nueva contraseña
                </button>
              }
            </div>
          </div>
        </form>
        <div class="text-secondary mt-3 text-center">
          <a [routerLink]="['/login']" class="text-white">Volver al inicio</a>
        </div>
      </div>
    </div>
  </body>
</html>
