// src/app/components/Admin/Layouts/header/header.component.ts
import { Router, RouterLink } from '@angular/router';
import { User } from '@interfaces/User';

import { Component, inject, input } from '@angular/core';
import { AuthService } from '@services/auth.service';

@Component({
  selector: 'app-header',
  imports: [RouterLink],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css',
})
export class HeaderComponent {
  user = input<User>({
    id: 0,
    name: '',
    paternal_surname: '',
    maternal_surname: '',
    rut: '',
    email: '',
    status: 0,
  });
  nameAvatar = input<string>('');

  private authService = inject(AuthService);
  private router = inject(Router);

  public loading: boolean = false;
  public validationErrors: string[] = [];
  public showPassword: boolean = false;
  public errorMessage: string = '';
  public successMessage: string = '';

  logout(): void {
    this.authService.logout().subscribe({
      next: (response: string) => {
        this.loading = false;
        this.router.navigate(['/']);
      },
      error: (error) => {
        this.loading = false;
        this.errorMessage = error;
      },
    });
  }
}

<header class="navbar navbar-expand-md d-print-none bg-primary">
  <div class="container">
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbar-menu"
      aria-controls="navbar-menu"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon text-white"></span>
    </button>
    <h1
      class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal pe-md-3 pe-0"
    >
      <a [routerLink]="['/admin/dashboard']">
        <img
          src="/assets/img/logos/logo-blanco.png"
          width="110"
          height="32"
          alt="logo-ima"
          class="navbar-brand-image"
        />
      </a>
    </h1>
    <div class="navbar-nav order-md-last flex-row">
      <div class="nav-item d-none d-md-flex me-3">
        <div class="btn-list">
          <a href="/" class="btn btn-primary" target="_blank" rel="noreferrer">
            <!-- Download SVG icon from http://tabler-icons.io/i/brand-github -->
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="icon icon-tabler icons-tabler-outline icon-tabler-world-www"
            >
              <path stroke="none" d="M0 0h24v24H0z" fill="none" />
              <path d="M19.5 7a9 9 0 0 0 -7.5 -4a8.991 8.991 0 0 0 -7.484 4" />
              <path d="M11.5 3a16.989 16.989 0 0 0 -1.826 4" />
              <path d="M12.5 3a16.989 16.989 0 0 1 1.828 4" />
              <path d="M19.5 17a9 9 0 0 1 -7.5 4a8.991 8.991 0 0 1 -7.484 -4" />
              <path d="M11.5 21a16.989 16.989 0 0 1 -1.826 -4" />
              <path d="M12.5 21a16.989 16.989 0 0 0 1.828 -4" />
              <path d="M2 10l1 4l1.5 -4l1.5 4l1 -4" />
              <path d="M17 10l1 4l1.5 -4l1.5 4l1 -4" />
              <path d="M9.5 10l1 4l1.5 -4l1.5 4l1 -4" />
            </svg>
            Sitio Web
          </a>
        </div>
      </div>

      <div class="nav-item dropdown">
        <a
          href="#"
          class="nav-link d-flex lh-1 text-reset p-0"
          data-bs-toggle="dropdown"
          aria-label="Open user menu"
        >
          <span class="avatar avatar-sm">{{ nameAvatar() }}</span>

          <div class="d-none d-xl-block ps-2 text-white">
            <div>{{ user().name }} {{ user().paternal_surname }}</div>
            <div class="small mt-1 text-white">{{ user().rut }}</div>
          </div>
        </a>
        <div
          class="dropdown-menu dropdown-menu-end dropdown-menu-arrow"
          data-bs-theme="light"
        >
          <a
            [routerLink]="['/admin/users/profile-update']"
            class="dropdown-item"
            >Mi Perfil</a
          >
          <a
            [routerLink]="['/admin/users/password-update']"
            class="dropdown-item"
            >Cambiar contraseña</a
          >
          <button (click)="logout()" class="dropdown-item">
            Cerrar sesión
          </button>
        </div>
      </div>
    </div>
  </div>
</header>

// src/components/Layouts/App/Header.vue
<template>
    <header class="navbar navbar-expand-md d-print-none sticky-top bg-primary shadow-sm" data-bs-theme="light">
        <div class="container-fluid">
            <button class="navbar-toggler text-white" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbar-menu" aria-controls="navbar-menu" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <h1 class="navbar-brand navbar-brand-autodark d-none-navbar-horizontal">
                <router-link to="/admin/home">
                    <img src="/img/logos/logo.png" alt="logo-muniarica" class="navbar-brand-image" />
                </router-link>
            </h1>
            <div v-if="isAuthenticated" class="navbar-nav flex-row order-md-last">
                <div class="d-none d-md-flex">
                    <span class="nav-link text-white">
                        Hola, {{ nombre }} </span>
                    <div class="vr"></div>
                </div>
                <div class="d-none d-md-flex">
                    <a href="#" class="nav-link text-white">
                        <!-- Download SVG icon from http://tabler-icons.io/i/bell -->
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                            stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                            class="me-2 icon icon-tabler icons-tabler-outline icon-tabler-user">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                            <path d="M8 7a4 4 0 1 0 8 0a4 4 0 0 0 -8 0" />
                            <path d="M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2" />
                        </svg>
                        Perfil:&ensp;
                        <span v-for="(item, index) in roles" :key="index">
                            {{ item }} &ensp;
                        </span>
                    </a>
                    <div class="vr"></div>
                    <div class="nav-item dropdown d-none d-md-flex">
                        <a href="#" class="nav-link btn btn-ghost-primary text-white dropdown-toggle"
                            data-bs-toggle="dropdown">
                            <!-- Download SVG icon from http://tabler-icons.io/i/bell -->
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                stroke-linejoin="round"
                                class="icon icon-tabler icons-tabler-outline icon-tabler-settings">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                <path
                                    d="M10.325 4.317c.426 -1.756 2.924 -1.756 3.35 0a1.724 1.724 0 0 0 2.573 1.066c1.543 -.94 3.31 .826 2.37 2.37a1.724 1.724 0 0 0 1.065 2.572c1.756 .426 1.756 2.924 0 3.35a1.724 1.724 0 0 0 -1.066 2.573c.94 1.543 -.826 3.31 -2.37 2.37a1.724 1.724 0 0 0 -2.572 1.065c-.426 1.756 -2.924 1.756 -3.35 0a1.724 1.724 0 0 0 -2.573 -1.066c-1.543 .94 -3.31 -.826 -2.37 -2.37a1.724 1.724 0 0 0 -1.065 -2.572c-1.756 -.426 -1.756 -2.924 0 -3.35a1.724 1.724 0 0 0 1.066 -2.573c-.94 -1.543 .826 -3.31 2.37 -2.37c1 .608 2.296 .07 2.572 -1.065z" />
                                <path d="M9 12a3 3 0 1 0 6 0a3 3 0 0 0 -6 0" />
                            </svg>
                            Configuración
                        </a>
                        <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-end dropdown-menu-card">
                            <router-link class="dropdown-item py-3" :to="{ name: 'Perfil' }">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                    fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                    stroke-linejoin="round"
                                    class="icon icon-tabler icons-tabler-outline icon-tabler-user-scan  me-2">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                    <path d="M10 9a2 2 0 1 0 4 0a2 2 0 0 0 -4 0" />
                                    <path d="M4 8v-2a2 2 0 0 1 2 -2h2" />
                                    <path d="M4 16v2a2 2 0 0 0 2 2h2" />
                                    <path d="M16 4h2a2 2 0 0 1 2 2v2" />
                                    <path d="M16 20h2a2 2 0 0 0 2 -2v-2" />
                                    <path d="M8 16a2 2 0 0 1 2 -2h4a2 2 0 0 1 2 2" />
                                </svg>
                                Mis Datos</router-link>
                            <router-link class="dropdown-item py-3" :to="{ name: 'Contrasena' }">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                    fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                    stroke-linejoin="round"
                                    class="icon icon-tabler icons-tabler-outline icon-tabler-lock me-2">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                                    <path
                                        d="M5 13a2 2 0 0 1 2 -2h10a2 2 0 0 1 2 2v6a2 2 0 0 1 -2 2h-10a2 2 0 0 1 -2 -2v-6z" />
                                    <path d="M11 16a1 1 0 1 0 2 0a1 1 0 0 0 -2 0" />
                                    <path d="M8 11v-4a4 4 0 1 1 8 0v4" />
                                </svg>
                                Cambiar Contraseña</router-link>
                        </div>
                    </div>
                    <div class="vr"></div>
                    <a @click="logout()" href="#" class="nav-link btn btn-ghost-primary text-white">
                        Cerrar sesión</a>
                </div>
            </div>
        </div>
    </header>
</template>
<script setup>
import { ref, computed } from "vue";
import { useRouter } from "vue-router";
import { useAuthStore } from '@/stores/auth';
import { useToast } from 'vue-toast-notification';
import 'vue-toast-notification/dist/theme-bootstrap.css';

const router = useRouter();
const authStore = useAuthStore();
const $toast = useToast();
const isAuthenticated = computed(() => authStore.isAuthenticated());
const roles = computed(() => authStore.roles);
const nombre = computed(() => authStore.user.nombre);


const logout = async () => {
    try {
        const { message } = await authStore.logout();
        $toast.info(message, {
            position: 'top-right'
        });
        router.push({ name: 'Login' });

    } finally { }
};

</script>
<style scoped>
.navbar-brand-image {
    width: 255px;
    height: auto;
}

.vr {
    display: inline-block;
    align-self: stretch;
    width: 1px;
    min-height: 1em;
    background-color: #ccc;
    opacity: .25;
    margin: 10px;
}

.dropdown-item:hover,
.dropdown-item:focus {
    color: inherit;
    text-decoration: none;
    background-color: rgba(97, 104, 118, 0.09);
}
</style>
